# Generated by Django 4.1.2 on 2022-10-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('FoodType', models.CharField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('StreetAddress', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
            ],
        ),
    ]
