# Generated by Django 4.1.2 on 2022-10-23 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0002_remove_detail_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='FoodType',
            field=models.CharField(choices=[('Beef Stroganoff', 'Beef Stroganoff'), ('Reuben', 'Reuben'), ('Sanwich', 'Sanwich'), ('Waldorf Salad', 'Waldorf Salad'), ('French Fries', 'French Fries'), ('Caesar Salad', 'Caesar Salad'), ('Chiken la King', 'Chiken la King'), ('Lobster', 'Lobster'), ('Salisbury Steak', 'Salisbury Steak'), ('Baked Alaska', 'Baked Alaska')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
